version: '2'

services:
  drupal:
    image: drupal
    ports:
       - "8081:80"
    volumes:
      - modules:/var/www/html/modules
      - profiles:/var/www/html/profiles
      - themes:/var/www/html/themes
      - sites:/var/www/html/sites
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: not_sure

volumes:
  modules:
  profiles:
  sites:
  themes:

